name: fpho
dependencies:
  # Infrastructure
  - ipython  # optional
  - pyyaml
  # Scientific computing
  - numpy>=1.14
  - scipy>=1.1.0
  - matplotlib
  - h5py
  - numba>=0.43.0
  # Astro
  - astropy
  # Inference
  - dynesty # optional
  - pip:
    - littlemcmc=0.2.*
  # Optional but recommended
  - pycuda
  - mpi4py>=3.1.0

# --- via setup.py ---
# forcepho