name: force
channels:
  - conda-forge
dependencies:
  # Infrastructure
  - pip
  - ipython  # optional
  - matplotlib  # optional
  - pyyaml
  - pybind11
  # Scientific computing
  - numpy>=1.14,<1.22
  - scipy>=1.1.0
  - h5py
  - numba>=0.51.0
  # Astro
  - astropy
  - regions
  - galsim  # optional, for testing
  # Inference
  - pip:
    - littlemcmc==0.2.*
  # Optional but recommended
  #- mpi4py>=3.1.0
  # get via pip install git+https://github.com/mpi4py/mpi4py
